export const FreshHero = {
  name: "Nameless Warrior",
  level: 1,
  xp: 0,
  levelXP: 20,
  hp: 6,
  maxHP: 6,
  damageDie: 6,
  armorDie: 0,
  deflectDie: 0,
  isCloaked: false,
  gold: 0,
  equipment: [],
  felledFoes: [],
};
